pub_hdrs = h{**}

./: $pub_hdrs

# Install into the tree_sitter/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/tree_sitter/
  install.subdirs = true
}
