intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/tree_sitter/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{tree-sitter}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
# Note that we only compile lib.c because Tree-sitter uses a unity build
# where lib.c includes all the other .c files.
#
lib{tree-sitter}: c{lib} h{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

#obja{*}: c.poptions += -DTREE_SITTER_STATIC_BUILD
#objs{*}: c.poptions += -DTREE_SITTER_SHARED_BUILD

# Export options.
#
lib{tree-sitter}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

#liba{tree-sitter}: c.export.poptions += -DTREE_SITTER_STATIC
#libs{tree-sitter}: c.export.poptions += -DTREE_SITTER_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{tree-sitter}: bin.lib.version = "-$version.project_id"
else
  lib{tree-sitter}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
