intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/tree_sitter/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{tree-sitter}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
# Note that we only compile lib.c because Tree-sitter uses a unity build
# where lib.c includes all the other .c files.
#
lib{tree-sitter}: libul{tree-sitter}: c{lib} h{**} $impl_libs $intf_libs

# Deal with Windows symbol exports for the dynamic library. Upstream tree-sitter
# doesn't annotate its API with __declspec(dllexport), so we have to rely on
# build2's auto symbol export mechanisms. The exact strategy we use depends
# heavily on the toolchain.
#
# If we are using MSVC (win32-msvc), the cleanest approach is to extract the
# exported symbols from the compiled object files and synthesize a module
# definition file (.def) that we then pass to the linker.
#
libs{tree-sitter}: def{tree-sitter}: include = ($c.target.system == 'win32-msvc')
                   def{tree-sitter}: libul{tree-sitter}

# For GNU-style toolchains targeting Windows (like MinGW or Clang with the GNU
# ABI), synthesizing a .def file is unnecessary. Instead, we can just instruct
# the linker to export all symbols from the object files directly. Note that we
# have to be careful with Clang here: it can target both the MSVC ABI (which
# uses the .def file approach above) and the GNU ABI. So we explicitly exclude
# the win32-msvc target system when matching Clang on Windows.
#
if ($c.target.system == 'mingw32' || \
    ($c.target.class == 'windows' && $c.id == 'clang' \
                                  && $c.target.system != 'win32-msvc'))
  c.loptions += -Wl,--export-all-symbols


# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

#obja{*}: c.poptions += -DTREE_SITTER_STATIC_BUILD
#objs{*}: c.poptions += -DTREE_SITTER_SHARED_BUILD

# Export options.
#
lib{tree-sitter}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

#liba{tree-sitter}: c.export.poptions += -DTREE_SITTER_STATIC
#libs{tree-sitter}: c.export.poptions += -DTREE_SITTER_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{tree-sitter}: bin.lib.version = "-$version.project_id"
else
  lib{tree-sitter}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
